### PR TITLE
added some better css for the go to details button

### PR DESCRIPTION
**Pull request by kiyohan**

### CODE REVIEW

**Comment by kiyohan** [comment]
Screenshot from 2024-10-03 17-08-06

**Comment by gopavasanth** [comment]
Hi @kiyohan , could you please change the text to "Learn more" instead of "Go to details"?

**Comment by kiyohan** [comment]
yeah definitely

**Comment by kiyohan** [comment]
image

**Review by gopavasanth — APPROVED** [review]
LGTM!

**Pull request merged**
