### PR TITLE
Added search bar functionality in tool

### PR DESCRIPTION
**Pull request by varun-s22**
# What this PR does
* Adds search bar to the tool
* Added pagination to the main page
* Added /search route
* Updated .gitignore
* Removed tools.db from database dir
* Added missing requirements to requirement.txt
* Fixed README.md

# What it looks like

### Search bar
Screenshot 2023-08-19 at 04 15 45

### Pagination (one page contains 50 tools)
Screenshot 2023-08-19 at 04 16 24

> Note: This PR is raised as a part of WIkimania Hackathon 2023

### CODE REVIEW

**Comment by sohomdatta1** [comment]
@varun-s22 Can you rebase on top of master ?

**Comment by sohomdatta1** [comment]
Also um, remove any changes to tools.db

**Comment by varun-s22** [comment]
Lets add tools.db in .gitignore

**Review by gopavasanth — APPROVED** [review]

**Comment by sohomdatta1** [comment]
Will pull this over when I get time

**Comment by varun-s22** [comment]
i was yet to test this lol

**Pull request merged**
